### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by raphaelfavier** [strasdat/ScaViSLAM#14]
There are several issues with the current installation process explained in README:
# 
# A - Sophus install:

there are not CMakeLists.txt file in the git branch anymore.

Adding the following works:

SET(PROJECT_NAME Sophus)

PROJECT(${PROJECT_NAME})
CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

SET (CMAKE_VERBOSE_MAKEFILE ON)

IF( NOT CMAKE_BUILD_TYPE )
   SET( CMAKE_BUILD_TYPE Release )
ENDIF()

IF (CMAKE_COMPILER_IS_GNUCXX )
   SET(CMAKE_CXX_FLAGS_DEBUG  "-O0 -g")
   SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -g ")

  ADD_DEFINITIONS("-Wall -Werror -Wno-unused-variable
                   -Wno-unused-but-set-variable -Wno-unknown-pragmas ")
ENDIF()

SET (INCLUDE_DIRS "../eigen3/")

SET (CLASSES  se3
              so3
              sim3)

SET (SOURCES)

FOREACH(class ${CLASSES})
  LIST(APPEND SOURCES sophus/${class}.cpp sophus/${class}.h)
ENDFOREACH(class)

INCLUDE_DIRECTORIES(${INCLUDE_DIRS})
ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCES})
# 
# B- VisionTools:

there are not CMakeLists.txt file in the git branch anymore.
adding the following works:

SET(PROJECT_NAME VisionTools)

PROJECT(${PROJECT_NAME})
CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

SET (CMAKE_VERBOSE_MAKEFILE ON)

IF( NOT CMAKE_BUILD_TYPE )
   SET( CMAKE_BUILD_TYPE Release )
ENDIF()

IF (CMAKE_COMPILER_IS_GNUCXX )
   SET(CMAKE_CXX_FLAGS_DEBUG  "-O0 -g")
   SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -g ")

  ADD_DEFINITIONS("-Wall -Werror -Wno-unused-variable
                   -Wno-unused-but-set-variable -Wno-unknown-pragmas ")
ENDIF()

SET (INCLUDE_DIRS "../eigen3/"
                  "../opencv2/include/opencv"
                  "../opencv2/include/"
                  "../opencv2/modules/core/include"
                  "../opencv2/modules/imgproc/include"
                  "../opencv2/modules/video/include"
                  "../opencv2/modules/features2d/include"
                  "../opencv2/modules/flann/include"
                  "../opencv2/modules/objdetect/include"
                  "../opencv2/modules/calib3d/include"
                  "../opencv2/modules/ml/include"
                  "../opencv2/modules/highgui/include"
                  "../opencv2/modules/legacy/include"
                  "../opencv2/modules/contrib/include"
                  "../Pangolin/"
                  "../Pangolin/svs_build"
                  "../Sophus/")

LIST(APPEND CMAKE_LIBRARY_PATH ../opencv2/svs_build/lib/
                               ../Pangolin/svs_build/pangolin)

SET (LINK_DIRS )
SET (LIB_NAMES GL pangolin glut
               opencv_core opencv_features2d opencv_flann opencv_gpu
               opencv_highgui opencv_imgproc opencv_calib3d)

FOREACH(lib ${LIB_NAMES})
  FIND_LIBRARY(LIB_${lib} ${lib})
  IF (LIB_${lib})
    MESSAGE(STATUS "found library '${lib}': ${LIB_${lib}}")
  ELSE (LIB_${lib})
    MESSAGE(FATAL_ERROR "cannot find library '${lib}' - this will not work ...")
  ENDIF (LIB_${lib})
  LIST(APPEND LIBS ${LIB_${lib}})
ENDFOREACH(lib)

SET (CLASSES  draw2d
              draw3d
              sample
              performance_monitor
              linear_camera)

SET (SOURCES visiontools/gl_data.h
             visiontools/abstract_camera.h
             visiontools/accessor_macros.h
             visiontools/ringbuffer.h
             visiontools/stopwatch.h)

FOREACH(class ${CLASSES})
  LIST(APPEND SOURCES visiontools/${class}.cpp visiontools/${class}.h)
ENDFOREACH(class)

LINK_LIBRARIES (${PROJECT_NAME} ${LIBS})

INCLUDE_DIRECTORIES(${INCLUDE_DIRS})
ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCES})
# 
# C- minor issues:

Eigen3 is not extracted into a folder named eigen-eigen-3.0.3 but eigen-eigen-<serial>.
Replace
mv eigen-eigen-3.0.3/ eigen3
by
mv eigen-eigen-<serial>/ eigen3

cmake -DSUPPORT_CUDA=OFF .. does not set CUDA to OFF
changing it manually in the CMakeLists.txt file solves this issue

**Comment by strasdat** [comment]
Issue A and B are solved.

**Comment by jodafo** [comment]
Not sure if I should have had opened a new issue, if so apologies...

When following the readme I encountered some issues:

1:
"Check out and install g2o (fork with slightly modified cmake file):"
issue when cloning:
git clone git@github.com:strasdat/g2o.git
Cloning into g2o...
Permission denied (publickey).

solution: used git clone https://github.com/strasdat/g2o.git instead

2:
"Clone and install Pangolin (68d75c2d54450d90efd2e6e2cfcd72a6a599ef58)"
issue when making:
/home/ScaViSLAM/EXTERNAL/Pangolin/pangolin/ffmpeg.cpp: In member function ‘void     pangolin::FfmpegVideo::InitUrl(std::string, std::string, std::string)’:
/home/ScaViSLAM/EXTERNAL/Pangolin/pangolin/ffmpeg.cpp:191:47: error: ‘avcodec_open2’ was not declared in this scope

**Comment by strasdat** [comment]
1. 
   Thanks, I'll update the README.

2.
I think this is due to some recent API changes in the ffmpeg library.
Can you either try a newer version of Pangolin or turn ffmpeg support off in Pangolin.

**Comment by t-thanh** [comment]
error: ‘avcodec_open2’ could be solved by installing the new libavcodec of ffmpeg from https://launchpad.net/~jon-severinsson/+archive/ffmpeg

**Comment by strasdat** [comment]
nttputus, I think that should be fixed in the newest version of Pangolin. The problem was that the README was suggesting to checkout an older version (which worked fine for me on an older Ubuntu).

**Comment by jodafo** [comment]
Thank you for your answers.

I tried it with the newest Pangolin version -  and had to add a "#include <iostream>" in display.h to allow for compiling. (error: ‘cerr’ is not a member of ‘std’...)

Unfortunately the error "avcodec_open2 was not declared" persists. (Also, using locate I could only find libavcodec.so.52 on my system, and I guess version 53 or higher is requiered...)
Concerning building Pangolin without ffmpeg support: I couldn't find a CMakeParameter to turn it off.

So I followed nttputus advice and installed the latest ffmpeg version (i.e. 4:0.9.1) from https://launchpad.net/~jon-severinsson/+archive/ffmpeg. I now have libavcodec.so.53 and libavformat.so.53, which i used both for making pangolin. But I still get the same error (avcodec_open2 not declared..) 

Edit: 
Ok i figured out how to disable ffmpeg support - might be helpful for people that encounter the problem as well: just blank out the libavcodec.so location in the cmake params

Edit2:
Installing without cuda support doesn't seem to work:
cmake -DCUDA_SUPPORT=OFF ..
CUDA SUPPORT ON
PCL SUPPORT OFF
SSE 4.1  SUPPORT OFF
CMake Error at CMakeModules/FindCUDA.cmake:465 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:95 (FIND_PACKAGE)

**Comment by djoubert** [comment]
Hi All

I just finished installing ScaViSLAM, I found a couple of hacks to make it work on my system (Ubuntu 10.04 64 bit).

The avcodec_open2 problem results (I think) from the function not being present in the libavcodec/avcodec.h header file - I have v4:0.6.2 from the lucidbleed ppa installed. I replaced avcodec_open2 with avcodec_open, which is the supposedly now the obsolete version. Just remember to remove the last parameter in the call (which is 0). I don't know if this is a viable solution, but I finished compiling. 

The CUDA_SUPPORT flag doesn't work because the cmakelists.txt file has an error in it, 
IF (NOT CUDA_SUPPORT)
 SET(CUDA_SUPPORT ON) 
should be 
 SET(CUDA_SUPPORT OFF)

Except if I got this completely wrong.

**Comment by strasdat** [comment]
@jodafo, @djoubert: Thanks for the comments related to ffmpeg and pangolin! Please note that Pangolin is not supported by me but by stevenlovegrove, so please direct any issue related to Pangolin to https://github.com/stevenlovegrove/Pangolin.
(Also, please do not use my old Pangolin fork but the original repository from stevenlovegrove).

@djoubert: Yes, there is an error related to CUDA_SUPPORT. However, ideally I would like to have the following behavior.
CUDA support by default, which can be turned off using a flag. Do you have an idea how to realize this?

**Comment by siddahuja** [comment]
This is what i got when i tried to build Pangolin: 

$ make -j8
Scanning dependencies of target pangolin
[ 18%] [ 18%] [ 18%] [ 18%] [ 27%] [ 27%] [ 31%] Building CXX object pangolin/CMakeFiles/pangolin.dir/vars.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/widgets.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/video.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/plotter.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/display.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/firewire.cpp.o
[ 36%] Building CXX object pangolin/CMakeFiles/pangolin.dir/v4l.cpp.o
Building CXX object pangolin/CMakeFiles/pangolin.dir/ffmpeg.cpp.o
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/pangolin.h:34:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/video.h:31,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/video.cpp:28:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/pangolin.h:34:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/firewire.h:31,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/firewire.cpp:28:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/pangolin.h:34:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/v4l.h:31,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/v4l.cpp:29:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/widgets.h:32:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/widgets.cpp:28:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/pangolin.h:34:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/plotter.h:31,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/plotter.cpp:28:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
In file included from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/pangolin.h:34:0,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/ffmpeg.h:31,
                 from /home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/ffmpeg.cpp:28:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h: In constructor ‘pangolin::Attach::Attach(GLfloat)’:
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:13: error: ‘cerr’ is not a member of ‘std’
/home/sid/ScaViSLAM/EXTERNAL/Pangolin/pangolin/display.h:125:202: error: ‘endl’ is not a member of ‘std’
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/video.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/v4l.cpp.o] Error 1
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/firewire.cpp.o] Error 1
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/plotter.cpp.o] Error 1
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/widgets.cpp.o] Error 1
make[2]: **\* [pangolin/CMakeFiles/pangolin.dir/ffmpeg.cpp.o] Error 1
make[1]: **\* [pangolin/CMakeFiles/pangolin.dir/all] Error 2
make: **\* [all] Error 2

This is how i fixed it: Open display.h and add the following lines to the top :

#include &lt;iostream&gt;
#include &lt;sstream&gt;

Save and recompile.
